export default fakeArray = [

    {
        id: '2',
        image: '',
        status: 'Found',
        name: 'Haseeba',
        age: 'teen',
        gender: 'female',
        location: 'Lahore',
        description: 'xyz',
        disability: 'mental',
        mobile: '+92 306 7134632',
        post_By: 'Fayyaz'
    },
    {
        id: '3',
        image: '',
        status: 'Missing',
        name: 'Asif',
        age: 'teen',
        gender: 'male',
        location: 'Karachi',
        description: 'xyz',
        disability: 'mental',
        mobile: '+92 306 7134632',
        post_By: 'Naveed'
    },
    {
        id: '4',
        image: '',
        status: 'Found',
        name: 'Hamza',
        age: 'teen',
        gender: 'male',
        location: 'Gujranwala',
        description: 'xyz',
        disability: 'mental',
        mobile: '+92 306 7134632',
        post_By: 'Naveed'
    },
    {
        id: '5',
        image: '',
        status: 'Found',
        name: 'Mobeen Jan',
        age: 'teen',
        gender: 'male',
        location: 'Gulamabad',
        description: 'xyz',
        disability: 'mental',
        mobile: '+92 306 7134632',
        post_By: 'Fayyaz'
    },
    {
        id: '6',
        image: '',
        status: 'Missing',
        name: 'Faqeeha',
        age: 'teen',
        gender: 'female',
        location: 'Hedrabad',
        description: 'xyz',
        disability: 'mental',
        mobile: '+92 306 7134632',
        post_By: 'Fayyaz'
    },
    {
        id: '7',
        image: '',
        status: 'Found',
        name: 'Nimra',
        age: 'teen',
        gender: 'female',
        location: 'Lahore',
        description: 'xyz',
        disability: 'mental',
        mobile: '+92 306 7134632',
        post_By: 'Naveed'
    },
]